name: Deploy Laravel to cPanel

on:
  push:
    branches:
      - master 

jobs:
  web-deploy:
    name: 🎉 Deploying Code to cPanel
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v4

      - name: 📂 Sync files via FTP
        uses: SamKirland/FTP-Deploy-Action@v4.3.5
        with:
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          port: 21
          server-dir: ./
          exclude: |
            **/.git**
            **/.git**/**
            **/node_modules/**
            **/vendor/**
            .env
            storage/*.key
            storage/logs/*